// Code generated by MockGen. DO NOT EDIT.
// Source: withered/server/domain (interfaces: Dispatcher)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/dispatcher_mock.go -package=mocks . Dispatcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "withered/server/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockDispatcher) Dispatch(ctx context.Context, sessionID domain.SessionID, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", ctx, sessionID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockDispatcherMockRecorder) Dispatch(ctx, sessionID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockDispatcher)(nil).Dispatch), ctx, sessionID, data)
}

// DispatchControl mocks base method.
func (m *MockDispatcher) DispatchControl(ctx context.Context, sessionID domain.SessionID, event any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchControl", ctx, sessionID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchControl indicates an expected call of DispatchControl.
func (mr *MockDispatcherMockRecorder) DispatchControl(ctx, sessionID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchControl", reflect.TypeOf((*MockDispatcher)(nil).DispatchControl), ctx, sessionID, event)
}

// RemoveSession mocks base method.
func (m *MockDispatcher) RemoveSession(sessionID domain.SessionID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveSession", sessionID)
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockDispatcherMockRecorder) RemoveSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockDispatcher)(nil).RemoveSession), sessionID)
}
