// Code generated by MockGen. DO NOT EDIT.
// Source: withered/server/domain (interfaces: RoomManager)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/room_manager_mock.go -package=mocks . RoomManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "withered/server/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomManager is a mock of RoomManager interface.
type MockRoomManager struct {
	ctrl     *gomock.Controller
	recorder *MockRoomManagerMockRecorder
	isgomock struct{}
}

// MockRoomManagerMockRecorder is the mock recorder for MockRoomManager.
type MockRoomManagerMockRecorder struct {
	mock *MockRoomManager
}

// NewMockRoomManager creates a new mock instance.
func NewMockRoomManager(ctrl *gomock.Controller) *MockRoomManager {
	mock := &MockRoomManager{ctrl: ctrl}
	mock.recorder = &MockRoomManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomManager) EXPECT() *MockRoomManagerMockRecorder {
	return m.recorder
}

// GetRoom mocks base method.
func (m *MockRoomManager) GetRoom(ctx context.Context, sessionID domain.SessionID) (domain.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, sessionID)
	ret0, _ := ret[0].(domain.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockRoomManagerMockRecorder) GetRoom(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockRoomManager)(nil).GetRoom), ctx, sessionID)
}
