---
- name: CRDTブログ デプロイ
  hosts: all
  become: true
  vars:
    app_repo: "https://github.com/touka-aoi/parallel-vs-single.git"
    app_branch: "main"
    app_dir: "/opt/crdt-blog"
    dotenv_private_key: "{{ lookup('env', 'DOTENV_PRIVATE_KEY_PRODUCTION') }}"

  roles:
    - docker
    - app
