// Code generated by MockGen. DO NOT EDIT.
// Source: withered/server/domain (interfaces: PubSub)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/pubsub_mock.go -package=mocks . PubSub
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "withered/server/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPubSub is a mock of PubSub interface.
type MockPubSub struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubMockRecorder
	isgomock struct{}
}

// MockPubSubMockRecorder is the mock recorder for MockPubSub.
type MockPubSubMockRecorder struct {
	mock *MockPubSub
}

// NewMockPubSub creates a new mock instance.
func NewMockPubSub(ctrl *gomock.Controller) *MockPubSub {
	mock := &MockPubSub{ctrl: ctrl}
	mock.recorder = &MockPubSubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSub) EXPECT() *MockPubSubMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPubSub) Publish(ctx context.Context, topic domain.Topic, msg domain.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", ctx, topic, msg)
}

// Publish indicates an expected call of Publish.
func (mr *MockPubSubMockRecorder) Publish(ctx, topic, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPubSub)(nil).Publish), ctx, topic, msg)
}

// Subscribe mocks base method.
func (m *MockPubSub) Subscribe(topic domain.Topic) <-chan domain.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", topic)
	ret0, _ := ret[0].(<-chan domain.Message)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockPubSubMockRecorder) Subscribe(topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockPubSub)(nil).Subscribe), topic)
}

// Unsubscribe mocks base method.
func (m *MockPubSub) Unsubscribe(topic domain.Topic, ch <-chan domain.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", topic, ch)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockPubSubMockRecorder) Unsubscribe(topic, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockPubSub)(nil).Unsubscribe), topic, ch)
}
